version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
endGatewayCulling = false
beaconBeamCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
minecraft = true
